name: Test
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Test app
        run: npm run test
