# Simple workflow for deploying static content to GitHub Pages
name: Test
on:
  push
  pull_request
jobs:
  runs-on: ubuntu-latest
  steps:
  -name: Get repository
    uses: actions/checkout@v2
  -name: Install dependencies
    run: npm ci
  -name: Test app
    run: npm run test
    